version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "5005:5005"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/demo
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    volumes:
      - .:/home/gradle/project
#      - ~/.gradle:/home/gradle/.gradle
#      - ./build/classes:/home/gradle/project/build/classes
#      - ./build/resources:/home/gradle/project/build/resources
#    command: sh -c "gradle clean build --continuous && java -Dspring.devtools.restart.enabled=true -jar /app.jar"
    restart: always

volumes:
  postgres-data:
